c_compiler:
  - gcc
c_compiler_version:
  - 7
cxx_compiler:
  - gxx
cxx_compiler_version:
  - 7
libgomp:
  - 7
channel_sources:
  - conda-forge,defaults
channel_targets:
  - conda-forge main
zip_keys:
  -
    - c_compiler_version
    - cxx_compiler_version
