package:
  name: rifdock
  version: 0.9.9ece4162b79

source:
  git_url: https://github.com/rifdock/rifdock.git
  git_rev: 305f8a004f28c37b451d4964ed38bd9ecfb02516
  git_depth: 1
  patches:
    - patch-rifdock-for-conda-build.diff

requirements:
  build:
    - python=2.7
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake=3.19
    - ninja=1.10
  host:
    - binutils
    - libboost=1.65
    - libgomp
    - zlib
    - rosetta_omp
  run:
    - zlib
    - rosetta_omp

test:
  commands:
    - rifgen --help
    - rif_dock_test --help

about:
  home: https://github.com/rifdock/rifdock
  license: Apache License, Version 2.0
  license_file: LICENSE
  summary: Rifdock Library for Conformational Search
