package:
  name: rifdock
  version: 0.9.9ece4162b79

source:
  git_url: https://github.com/rifdock/rifdock.git
  git_rev: 9ece4162b790a2e1f386638a28f74206205e352
  git_depth: 1 
  patches:
    - patch-rifdock-for-conda-build.diff

requirements:
  build:
    - python=2.7
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake=3.20
    - ninja=1.10
  host:
    - binutils
    - libboost=1.65
    - libgomp      # [linux64]
    - llvm-openmp  # [osx]
    - libcxx       # [osx]
    - zlib
    - rosetta_omp
  run:
    - zlib
    - rosetta_omp

test:
  commands:
    - rifgen --help
    - rif_dock_test --help

about:
  home: https://github.com/rifdock/rifdock
  license: Apache License, Version 2.0
  license_file: LICENSE
  summary: Rifdock Library for Conformational Search
