#!/bin/bash -il
set -e
set -x

if [ "$(uname -m)" = "x86_64" ]; then
   export supkg="gosu"
else
   export supkg="su-exec"
fi

# give sudo permission for conda user to run apt-get (user creation is postponed
# to the entrypoint, so we can create a user with the same id as the host)
echo 'conda ALL=NOPASSWD: /usr/bin/apt-get' >> /etc/sudoers

export PATH=/opt/conda/bin:$PATH && \
    conda config --set show_channel_urls True && \
    conda update --all --yes && \
    conda clean -tipy

# Install conda-provided tools we need and can get right now
export PATH="/opt/conda/bin:${PATH}" && \
    conda install --yes --quiet perl=5.26 && \
    conda clean -tipsy

# Install docker tools
export PATH="/opt/conda/bin:${PATH}" && \
    conda install --yes conda-forge::$supkg && \
    export CONDA_SUEXEC_INFO=( `conda list $supkg | grep $supkg` ) && \
    echo "$supkg ${CONDA_SUEXEC_INFO[1]}" >> /opt/conda/conda-meta/pinned && \
    conda install --yes conda-forge::tini && \
    export CONDA_TINI_INFO=( `conda list tini | grep tini` ) && \
    echo "tini ${CONDA_TINI_INFO[1]}" >> /opt/conda/conda-meta/pinned && \
    conda clean -tipsy

# Lucky group gets permission to write in the conda dir
groupadd -g 32766 lucky
chgrp -R lucky /opt/conda && chmod -R g=u /opt/conda
